baseUrl=https://www.saucedemo.com/
browser=chrome
platform=desktop
implicitWaitSeconds=5
explicitWaitSeconds=15
retryCount=1
appiumServerUrl=http://127.0.0.1:4723
bStackAppiumServer=https://hub-cloud.browserstack.com/wd/hub
newAppiumCommandTimeout=60